function [R, rhsReg] = build_ec_regularization(mesh, uCurrent, uRef, weights)
%BUILD_EC_REGULARIZATION Regularization for log10(EC) inversion.

    [Dx, Dy, Dz, Dxx, Dyy, Dzz] = make_property_difference_operators(mesh);

    R = [ ...
        sqrt(weights.beta) * speye(numel(uCurrent)); ...
        sqrt(weights.ax) * Dx; ...
        sqrt(weights.ay) * Dy; ...
        sqrt(weights.az) * Dz; ...
        sqrt(weights.cx) * Dxx; ...
        sqrt(weights.cy) * Dyy; ...
        sqrt(weights.cz) * Dzz];

    rhsReg = [ ...
        sqrt(weights.beta) * (uRef - uCurrent); ...
        -sqrt(weights.ax) * (Dx * uCurrent); ...
        -sqrt(weights.ay) * (Dy * uCurrent); ...
        -sqrt(weights.az) * (Dz * uCurrent); ...
        -sqrt(weights.cx) * (Dxx * uCurrent); ...
        -sqrt(weights.cy) * (Dyy * uCurrent); ...
        -sqrt(weights.cz) * (Dzz * uCurrent)];
end

