function [R, rhsReg] = build_ec_background_anomaly_regularization(mesh, param, uBgCurrent, uAnomCurrent, uBgRef, uAnomRef, weights)
%BUILD_EC_BACKGROUND_ANOMALY_REGULARIZATION Regularization for u = background(z) + anomaly(x,z).

    [Dx, Dy, Dz, Dxx, Dyy, Dzz] = make_property_difference_operators(mesh);
    [DzBg, DzzBg] = localBackgroundDifferenceOperators(param.zCenters);
    bgProfileCurrent = param.basisZ * uBgCurrent;

    Rbg = [ ...
        sqrt(weights.betaBg) * speye(numel(uBgCurrent)); ...
        sqrt(weights.z1Bg) * (DzBg * param.basisZ); ...
        sqrt(weights.z2Bg) * (DzzBg * param.basisZ)];

    rhsBg = [ ...
        sqrt(weights.betaBg) * (uBgRef - uBgCurrent); ...
        -sqrt(weights.z1Bg) * (DzBg * bgProfileCurrent); ...
        -sqrt(weights.z2Bg) * (DzzBg * bgProfileCurrent)];

    Ranom = [ ...
        sqrt(weights.zeroMeanAnom) * param.Amean; ...
        sqrt(weights.betaAnom) * speye(numel(uAnomCurrent)); ...
        sqrt(weights.axAnom) * Dx; ...
        sqrt(weights.ayAnom) * Dy; ...
        sqrt(weights.azAnom) * Dz; ...
        sqrt(weights.cxAnom) * Dxx; ...
        sqrt(weights.cyAnom) * Dyy; ...
        sqrt(weights.czAnom) * Dzz];

    rhsAnom = [ ...
        -sqrt(weights.zeroMeanAnom) * (param.Amean * uAnomCurrent); ...
        sqrt(weights.betaAnom) * (uAnomRef - uAnomCurrent); ...
        -sqrt(weights.axAnom) * (Dx * uAnomCurrent); ...
        -sqrt(weights.ayAnom) * (Dy * uAnomCurrent); ...
        -sqrt(weights.azAnom) * (Dz * uAnomCurrent); ...
        -sqrt(weights.cxAnom) * (Dxx * uAnomCurrent); ...
        -sqrt(weights.cyAnom) * (Dyy * uAnomCurrent); ...
        -sqrt(weights.czAnom) * (Dzz * uAnomCurrent)];

    R = blkdiag(Rbg, Ranom);
    rhsReg = [rhsBg; rhsAnom];
end

function [DzBg, DzzBg] = localBackgroundDifferenceOperators(zCenters)
    nZ = numel(zCenters);
    if nZ <= 1
        DzBg = sparse(0, nZ);
        DzzBg = sparse(0, nZ);
        return;
    end

    h = max(diff(zCenters(:)), eps);
    nRows1 = nZ - 1;
    rr = repelem((1:nRows1)', 2, 1);
    cc = [(1:nRows1)'; (2:nZ)'];
    vv = [-1 ./ h; 1 ./ h];
    DzBg = sparse(rr, cc, vv, nRows1, nZ);

    if nZ <= 2
        DzzBg = sparse(0, nZ);
    else
        nRows2 = nZ - 2;
        hLeft = h(1:end-1);
        hRight = h(2:end);
        denom = hLeft + hRight;
        rr = repelem((1:nRows2)', 3, 1);
        cc = [(1:nRows2)'; (2:nZ-1)'; (3:nZ)'];
        vv = [ ...
            2 ./ (hLeft .* denom); ...
            -2 .* (1 ./ hLeft + 1 ./ hRight) ./ denom; ...
            2 ./ (hRight .* denom)];
        DzzBg = sparse(rr, cc, vv, nRows2, nZ);
    end
end
